# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ali Iqrash
title: Wireless Communication Engineer
email: Aliiqrash01@gmail.com
phone: 01635154759
# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
#github_username:  AleeEqrash
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: ali-iqrash
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: aleeeqrash.github.io
  icon: fas fa-globe
  url: https://aleeeqrash.github.io/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profiles.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Ali Iqrash and I'm a Radio Communication Engineer with 4 years of experience in 2G, 3G, 4G, and 5G across multiple operators and vendors. Seeking to apply my expertise at Prudential. 

***I’m good at:***
  - **Python**: NumPy, Pandas, Scikit-learn, Seaborn, Matplotlib
  - **MATLAB & Simulink**
  - **Data Science**: Machine Learning, Data Analysis, Data Exploration
  - **Test Frameworks**: Pytest, Robot Framework, POSTMAN, SOAP

 
content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ORBIT - Bonn
        link: https://www.orbit.de/
        # link_text: boringcompany.com
        sub_title: Network Protocol Test Engineer 
        caption: November 2023 - Present
        quote: |
          Currently working for Deutsche Telekom in Device testing & Certification. And responsible for: 
        description: | # this will include new lines to allow paragraphs
            - Protocol Testing experience in LTE/5G NSA&SA/O-RAN Device.             
            - Handset and Chipsets for DT standards on network simulators.            
            - Writing 5G SA test cases and scenarios for handsets chipset testing.
            - Experience in the use of mobile phone testers or OTA chambers.             
            - Hand on experience in 3GPP standards for VoWiFi, ePDG, and IMS.             
            - Tracing tools: Accuver, QXDM, Shannon DM, CMW/CMX500. 
    #content:
      - layout: left
        title: MicroNova AG - Munich
        link: https://www.micronova.de/
        # link_text: boringcompany.com
        sub_title: Working Student – Telco Solutions  
        caption: February 2023 - October 2023
        quote: |
          Was working student and responsibilities were: 
        description: | # this will include new lines to allow paragraphs
            - Working on 5G Networking Slicing POC project for Telefonica.             
            - Working with development and design team for deployment and integration of slicing service catalogue as per 3GPP specifications.            
            - Understanding of 5G RAN and core functions.
    #content:
      - layout: left
        title: Huawei Technologies Co., Ltd. - Pakistan
        link: https://www.huawei.com/
        # link_text: boringcompany.com
        sub_title: Radio Access Network Integration Engineer 
        caption: October 2019 - November 2021
        quote: |
          Worked as Integration Engineer on Mobily-(KSA) project. And responsible for: 
        description: | # this will include new lines to allow paragraphs
            - Integration, Troubleshooting, Analyzing, and Optimization of network performance KPIs and architecture were key responsibilities.              
            - Integration of sites according to acceptance criteria for different scenarios i.e., 5G, LTE Carrier addition, Multi RAN to Single RAN, MIMO 4T4R, 32T32R, 64T64R.             
            - Managed a team of 5 engineers and delivered 1200 sites of NB-IoT expansion in 3 months.
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: API Testing using SOAP UI
        caption: November 2024 – January 2025
        #link: github.com/sproogen
        # link_text: Project Website
        #additional_links:
          #- title:  sproogen/modern-resume-theme
            #icon: fab fa-github
            #url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is a personal project undertaken for self-directed learning.
        description: | # this will include new lines to allow paragraphs
          - Learned SOAP API testing using mock servers.
          - Tested API functionality, performance, and error handling.
          - Developed a self-initiated project that evolved into a fully-fledged application.
          - Gained hands-on experience in API automation and quality assurance.
      - layout: left
        title: Implementation of SON function of MRO as xApp on Open-RAN based RIC
        caption: October 2022 – February 2023
        #link: github.com/sproogen
        # link_text: Project Website
        #additional_links:
          #- title:  sproogen/modern-resume-theme
            #icon: fab fa-github
            #url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          As Advnace Research Project during my Masters Degree at TU Ilmenau I did this project and learnt:
        description: | # this will include new lines to allow paragraphs
          - Installation and setup of ONOS RIC, RAN simulator and, apps. 
          - Adapting in-house SON function of MRO/MLB as a xApp using the specific Interface/APIs crowded by CNOS.
          - Design and implement a SON function for URLLC applications. based on the features supported by the RAN simulation.
          - Measurements and comparison of the results.
      - layout: left
        title: Real-Time Load Estimation of Cell in LTE Network  
        caption: November 2021 – July 2022
        #link: github.com/sproogen
        # link_text: Project Website
        #additional_links:
          #- title:  sproogen/modern-resume-theme
            #icon: fab fa-github
            #url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Completed this project as a Basic Research Project during the first year of my Master's at Kazan National Research Technical University. This project played a fundamental role in shaping my career.
        description: | # this will include new lines to allow paragraphs
          - The fundamental idea behind this was to estimate the LTE cell’s information load, using real-time signal, by decoding DCI messages in the LTE physical control channel and determining the number of unique identifiers. 
          - Implemented algorithm on SDRs and developed a prototype. 
          - Tested on more than 5 commercial sites of different vendors and successfully detected users with an efficiency of up to 90 percent. 
      - layout: left
        title: Enhancing Security via Speaker Recognition  
        caption: 2017 - 2018
        #link: github.com/sproogen
        # link_text: Project Website
        #additional_links:
          #- title:  sproogen/modern-resume-theme
            #icon: fab fa-github
            #url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Completed this project as my Final Year Project as part of my undergraduate degree at University of Sargodha.
        description: | # this will include new lines to allow paragraphs
          - Worked on real-time human speech processing, extraction of Mel-frequency Cepstral Coefficients (MFCC), and matching of voice signal’s unique features by Vector quantization (VQ) in MATLAB.
          - The developed system can be used for enhancing cyber security which overcomes the issues such as online banking where customers are prone to theft using fake identities. 
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Technische Universität Ilmenau
        caption: 2021 - Present
        sub_title: Master of Engineering (M.Eng.) - Communication and Signal Processing
        quote: >
          Established in 1894, The Technische Universität Ilmenau (TU Ilmenau) is a German public research university located in Ilmenau, Thuringia, central Germany, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the Germany but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Technische Universität Ilmenau (TU Ilmenau), I developed key technical competencies that have been fundamental to my career. I acquired in-depth knowledge of Cellular Communication Systems and Advanced Mobile Communication Systems, along with expertise in Adaptive Array Signal Processing and Digital Signal Processing. Additionally, I gained a strong understanding of Wireless Communication, including both source coding and channel coding techniques. I further expanded my skill set by studying advanced topics in mathematics and mathematical modeling of devices and systems, which enhanced my analytical and problem-solving abilities.
      - layout: left
        title: University of Sargodha 
        caption: 2014 - 2018
        sub_title: Bachelor of Engineering (B.E.) - Electrical Engineering 
        quote: >
          University of Sargodha is a renowned public university in Pakistan, known for its strong emphasis on research and development (R&D).
        description: | # this will include new lines to allow paragraphs
          During my time at the University of Sargodha, I majored in Wireless Mobile Communication, Optical Fiber, and Signal Processing. I acquired a comprehensive understanding of wave propagation, antenna theory, and antenna design, and mastered advanced techniques and algorithms for the transmission and processing of digital information. This rigorous academic foundation has been instrumental in refining my technical expertise and problem-solving abilities.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/AleeEqrash.github.io/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
